@startuml

Client -> Server : request
activate Server
note left 
单个查询流程
参数: 
string code, 
string startDate, endDate, 
int initialMethod, 
float percentOf6Points
end note

Client <- Server : response
note left
参数：
end note

deactivate Server

@enduml
