@startuml single

'单个浏览数据，已经完成获取数据'
Client -> getNewAxis : operate
activate getNewAxis
note left 
基本信息
int maxStep
int currentStep
int startStep(default 0)
已有数据
idList: list<int id>
closeList: list<float close>
methodList: list<int method>
dateList: list<string date>
maxStep: int
改变的数据
int xMax
int xMin
float yMax
float yMin
end note

getNewAxis -> : getCloseFromCodeAndDate()
activate CloseList
note left
获取收盘价
string code
string startDate
string endDate
end note

CloseList -> MehtodList: getMethodFromClose()
activate MehtodList
note left
获取method列表
list<float>
end note

MehtodList -> CloseList: methodList
deactivate MehtodList
CloseList -> Server: closeList
deactivate CloseList

Client <- Server : response
note left
单个返回结果
idList: list<int id>
closeList: list<float close>
methodList: list<int method>
maxStep: int
end note
deactivate Server

@enduml

