@startuml single
'单个获取trade数据'
'未开始'
Client -> Server : request
activate Server
note left 
int nowId = idList[nowStep],
float close = closeList[nowId],
int method = methodList[nowId],
bool buyOrSell(default True)
int tradeNum
float totalMoney(Client)
float currentMoney(Client)
float discretionaryMoney(Client)
end note

Server -> Account: implementAccountAlter()
activate Account
note left
int nowId
float close 
int method
bool buyOrSell(default True)
int tradeNum
float totalMoney(Client)
float currentMoney(Client)
float discretionaryMoney(Client)
end note

Account -> Voucher: generateVoucher()
activate Voucher
note left
int nowId
float close
float totalMoney
float currentMoney
float discretionaryMoney
bool buyOrSell
int tradeNum
end note

Voucher -> Account: list[int id, float close, int tradeNum]
deactivate Voucher

deactivate Account
@enduml
